### ISSUE TITLE
LVGL Support

### ISSUE THREAD

**Issue by Hannah-GBS** [buglloc/esphome-components#12]
I can't seem to get LVGL working with the axs15231 component (with a Lilygo T-Display S3 Long). 
If I set `update_interval` to `never` as the ESPHome docs request I just get a blank white display. 
If I comment it out (ie use default 1s) I get *some* of my LVGL page displayed but the 1s refresh causes it to glitch out a bunch.
I know the Lilygo docs say to only use LVGL 8.3.0, and afaik ESPHome uses 8.4.0 or higher, so is support for this display just not possible?

**Comment by ageurtse** [comment]
same problem for me, when using LVGL the display is very slow and it looks like the part that has to be updated isn't meshed up and not in the right place. 

See also a video off the problem [https://youtu.be/Yd0yymlYRNM]
I'm using LVGL from within ESPHome, threath [https://community.home-assistant.io/t/esp32-s3-3-5-inch-capacitive-touch-ips-module-320-480/768591/21?u=ageurtse]

**Comment by yashmulgaonkar** [comment]
+1
