### ISSUE TITLE
Touch coordinates incomplete

### ISSUE THREAD

**Issue by yashmulgaonkar** [buglloc/esphome-components#13]
Bud in touchscreen driver for vertical (portrait) orientation.
Touch coordinates max out at 47 for one of the axes even after calibration.
Here are the four corners.

21:55:41	[I]	[cal:105]	x=1, y=639, x_raw=627, y_raw=6
21:55:44	[I]	[cal:105]	x=47, y=639, x_raw=619, y_raw=169
21:55:48	[I]	[cal:105]	x=47, y=35, x_raw=10, y_raw=168
21:55:49	[I]	[cal:105]	x=4, y=35, x_raw=10, y_raw=16

**Comment by buglloc** [comment]
Hi, I rewrote the touch screen component (#15 15) a bit and I can't reproduce this problem. Сan you check if it helped you?

**Comment by yashmulgaonkar** [comment]
Appreciate the help! Will try it out in a bit.

**Comment by yashmulgaonkar** [comment]
OK this seems to work now! Thanks for your help!
